// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vetigo.Api;

#nullable disable

namespace Vetigo.Api.Migrations
{
    [DbContext(typeof(VetigoDbContext))]
    [Migration("20260809083333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Vetigo.Api.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<string>("RideName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Time")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distance = 18.399999999999999,
                            RideName = "Sunday Loop",
                            Time = 62.0
                        },
                        new
                        {
                            Id = 2,
                            Distance = 6.2000000000000002,
                            RideName = "Downhill Run",
                            Time = 18.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
